/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GoodMath;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import MiMath.Avanzadas;

/**
 *
 * @author HP
 */
public class Algebra extends javax.swing.JFrame {

    /**
     * Creates new form Algebra
     */
    public Algebra() {
        super("Álgebra");
        this.setLocation(450, 100);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonBack1 = new miSwing.BotonBack();
        miniEnca1 = new miSwing.miniEnca();
        jLabel1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        FA = new javax.swing.JTextField();
        FB = new javax.swing.JTextField();
        FC = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        RX1 = new javax.swing.JTextField();
        RX2 = new javax.swing.JTextField();
        FB1 = new javax.swing.JTextField();
        calculadora1 = new miSwing.Calculadora();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        botonBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBack1ActionPerformed(evt);
            }
        });
        jPanel1.add(botonBack1);
        botonBack1.setBounds(10, 10, 90, 30);
        jPanel1.add(miniEnca1);
        miniEnca1.setBounds(0, 0, 500, 0);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/FormulaGeneral.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 70, 460, 140);

        jLabel17.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 255));
        jLabel17.setText("Formula general");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(190, 220, 150, 23);

        jLabel18.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel18.setText("Valor de A:");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(100, 270, 80, 20);

        jLabel19.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel19.setText("Valor de B:");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(100, 310, 80, 20);

        jLabel20.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel20.setText("Valor de C:");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(100, 350, 80, 20);

        FA.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        FA.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        FA.setOpaque(false);
        FA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FAActionPerformed(evt);
            }
        });
        jPanel1.add(FA);
        FA.setBounds(180, 260, 60, 30);

        FB.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        FB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        FB.setOpaque(false);
        jPanel1.add(FB);
        FB.setBounds(180, 300, 60, 30);

        FC.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        FC.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        FC.setOpaque(false);
        FC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FCActionPerformed(evt);
            }
        });
        jPanel1.add(FC);
        FC.setBounds(180, 340, 60, 30);

        jLabel21.setFont(new java.awt.Font("Berlin Sans FB", 1, 16)); // NOI18N
        jLabel21.setText("X1:");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(280, 260, 30, 30);

        jLabel22.setFont(new java.awt.Font("Berlin Sans FB", 1, 16)); // NOI18N
        jLabel22.setText("X2:");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(280, 320, 24, 30);

        RX1.setEditable(false);
        RX1.setBackground(new java.awt.Color(255, 255, 255));
        RX1.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        RX1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        RX1.setOpaque(false);
        jPanel1.add(RX1);
        RX1.setBounds(310, 250, 100, 40);

        RX2.setEditable(false);
        RX2.setBackground(new java.awt.Color(255, 255, 255));
        RX2.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        RX2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        RX2.setOpaque(false);
        jPanel1.add(RX2);
        RX2.setBounds(310, 310, 100, 40);

        FB1.setEditable(false);
        FB1.setBackground(new java.awt.Color(255, 255, 255));
        FB1.setForeground(new java.awt.Color(255, 255, 255));
        FB1.setText("2");
        FB1.setBorder(null);
        jPanel1.add(FB1);
        FB1.setBounds(320, 250, 120, 30);

        calculadora1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculadora1ActionPerformed(evt);
            }
        });
        jPanel1.add(calculadora1);
        calculadora1.setBounds(300, 370, 60, 80);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FAActionPerformed

    private void FCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FCActionPerformed

    private void calculadora1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculadora1ActionPerformed
        double xr,x1,x2;
        DecimalFormat df= new DecimalFormat(".####");
        if(FA.getText().trim().isEmpty() || FB.getText().trim().isEmpty() || FC.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Para calcular la formula general llene todos los campos en el espacio de la formula general", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }else{
        int a = Integer.parseInt(FA.getText());
        int b = Integer.parseInt(FB.getText());
        double b1 = Avanzadas.Potencia(Integer.parseInt(FB.getText()),(Integer.parseInt(FB1.getText())));
        int c = Integer.parseInt(FC.getText());
        
        xr= Avanzadas.raiz((b1)-(4*a*c));
        if(xr >= 0){
            x1=(((-b)+xr)/(2*a));
            x2=(((-b)-xr)/(2*a));
            RX1.setText(""+df.format(x1));
            RX2.setText(""+df.format(x2));
        }else{
            JOptionPane.showMessageDialog(null, "No se puede calcular ya que es una raiz negativa");
        }
        }     
    }//GEN-LAST:event_calculadora1ActionPerformed

    private void botonBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBack1ActionPerformed
        Menu2 men2 = new Menu2();
        men2.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonBack1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Algebra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Algebra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Algebra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Algebra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Algebra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FA;
    private javax.swing.JTextField FB;
    private javax.swing.JTextField FB1;
    private javax.swing.JTextField FC;
    private javax.swing.JTextField RX1;
    private javax.swing.JTextField RX2;
    private miSwing.BotonBack botonBack1;
    private miSwing.Calculadora calculadora1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JPanel jPanel1;
    private miSwing.miniEnca miniEnca1;
    // End of variables declaration//GEN-END:variables
}
