/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GoodMath;

import MiMath.Convertidor;
import javax.swing.JOptionPane;
public class Convertidore extends javax.swing.JFrame {

    /**
     * Creates new form Convertidor
     */
    public Convertidore() {
        super("Convertidor");
        this.setLocation(450, 100);
        this.setResizable(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        miniEnca1 = new miSwing.miniEnca();
        botonBack1 = new miSwing.BotonBack();
        miEtiqueta1 = new miSwing.miEtiqueta();
        grados = new javax.swing.JTextField();
        miEtiqueta2 = new miSwing.miEtiqueta();
        miEtiqueta3 = new miSwing.miEtiqueta();
        jSeparator1 = new javax.swing.JSeparator();
        r2 = new javax.swing.JTextField();
        kilo = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        miEtiqueta4 = new miSwing.miEtiqueta();
        r1 = new javax.swing.JTextField();
        miEtiqueta5 = new miSwing.miEtiqueta();
        metros = new javax.swing.JTextField();
        miBoton1 = new miSwing.miBoton();
        miBoton2 = new miSwing.miBoton();
        miBoton3 = new miSwing.miBoton();
        miBoton4 = new miSwing.miBoton();
        miBoton5 = new miSwing.miBoton();
        jPanel2 = new javax.swing.JPanel();
        Resultado = new miSwing.miEtiqueta();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);
        jPanel1.add(miniEnca1);
        miniEnca1.setBounds(0, 0, 500, 105);

        botonBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBack1ActionPerformed(evt);
            }
        });
        jPanel1.add(botonBack1);
        botonBack1.setBounds(10, 370, 90, 91);

        miEtiqueta1.setText("Grados:");
        jPanel1.add(miEtiqueta1);
        miEtiqueta1.setBounds(30, 110, 70, 23);

        grados.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        grados.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(grados);
        grados.setBounds(100, 110, 50, 30);

        miEtiqueta2.setText("°");
        jPanel1.add(miEtiqueta2);
        miEtiqueta2.setBounds(150, 110, 10, 23);

        miEtiqueta3.setText("Radianes:");
        jPanel1.add(miEtiqueta3);
        miEtiqueta3.setBounds(30, 200, 90, 23);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(120, 210, 60, 10);

        r2.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        r2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(r2);
        r2.setBounds(120, 220, 59, 30);

        kilo.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        kilo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(kilo);
        kilo.setBounds(390, 180, 59, 30);

        jLabel28.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        jLabel28.setText("π radianes");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(190, 200, 90, 23);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(280, 110, 10, 140);

        miEtiqueta4.setText("Metros:");
        jPanel1.add(miEtiqueta4);
        miEtiqueta4.setBounds(290, 110, 70, 23);

        r1.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        r1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(r1);
        r1.setBounds(120, 170, 59, 30);

        miEtiqueta5.setText("Kilogramo:");
        jPanel1.add(miEtiqueta5);
        miEtiqueta5.setBounds(290, 180, 100, 23);

        metros.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        metros.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(metros);
        metros.setBounds(360, 110, 59, 30);

        miBoton1.setText("Grados a Radianes");
        miBoton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBoton1ActionPerformed(evt);
            }
        });
        jPanel1.add(miBoton1);
        miBoton1.setBounds(20, 310, 177, 27);

        miBoton2.setText("Radianes a Grados");
        miBoton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBoton2ActionPerformed(evt);
            }
        });
        jPanel1.add(miBoton2);
        miBoton2.setBounds(20, 270, 180, 27);

        miBoton3.setBackground(new java.awt.Color(255, 0, 51));
        miBoton3.setText("Metros a Millas");
        miBoton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBoton3ActionPerformed(evt);
            }
        });
        jPanel1.add(miBoton3);
        miBoton3.setBounds(310, 230, 150, 27);

        miBoton4.setBackground(new java.awt.Color(255, 0, 51));
        miBoton4.setText("Metros a Yardas");
        miBoton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBoton4ActionPerformed(evt);
            }
        });
        jPanel1.add(miBoton4);
        miBoton4.setBounds(310, 270, 160, 27);

        miBoton5.setBackground(new java.awt.Color(0, 204, 0));
        miBoton5.setText("Kilogramo a Libra");
        miBoton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBoton5ActionPerformed(evt);
            }
        });
        jPanel1.add(miBoton5);
        miBoton5.setBounds(310, 310, 170, 27);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));

        Resultado.setText("Resultado:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Resultado, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 5, Short.MAX_VALUE)
                .addComponent(Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(120, 400, 380, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miBoton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBoton2ActionPerformed
        if(!r1.getText().trim().isEmpty()){
            if(!r2.getText().trim().isEmpty()){
            String c = r1.getText().trim();
            String c2 = r2.getText().trim();
            double r = Convertidor.RadianesGrados(c, c2);
            Resultado.setText(c+"/"+c2+" pi radianes es igual a "+r+" grados");
            }
            else{
                JOptionPane.showMessageDialog(null, "Ingrese un valor de radianes", "Advertencia", JOptionPane.WARNING_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Ingrese un valor de radianes", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_miBoton2ActionPerformed

    private void miBoton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBoton1ActionPerformed
        if(!grados.getText().trim().isEmpty()){
            String c = grados.getText().trim();
            double r = Convertidor.GradosRadianes(c);
            Resultado.setText(c+" grados es igual a "+r+" radianes");
        }
        else{
            JOptionPane.showMessageDialog(null, "Ingrese un valor de grados", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_miBoton1ActionPerformed

    private void miBoton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBoton3ActionPerformed
        if(!metros.getText().trim().isEmpty()){
            String c = metros.getText().trim();
            double r = Convertidor.MetrosMillas(c);
            Resultado.setText(c+" metros es igual a "+r+" millas");
        }
        else{
            JOptionPane.showMessageDialog(null, "Ingrese un valor de metros", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_miBoton3ActionPerformed

    private void miBoton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBoton4ActionPerformed
        if(!metros.getText().trim().isEmpty()){
            String c = metros.getText().trim();
            double r = Convertidor.MetrosYardas(c);
            Resultado.setText(c+" metros es igual a "+r+" yardas");
        }
        else{
            JOptionPane.showMessageDialog(null, "Ingrese un valor de metros", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_miBoton4ActionPerformed

    private void miBoton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBoton5ActionPerformed
        if(!kilo.getText().trim().isEmpty()){
            String c = kilo.getText().trim();
            double r = Convertidor.KgramosLibras(c);
            Resultado.setText(c+" kilogramos es igual a "+r+" libras");
        }
        else{
            JOptionPane.showMessageDialog(null, "Ingrese un valor de kilogramos", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_miBoton5ActionPerformed

    private void botonBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBack1ActionPerformed
        Menu2 onj = new Menu2();
        onj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonBack1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Convertidore().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private miSwing.miEtiqueta Resultado;
    private miSwing.BotonBack botonBack1;
    private javax.swing.JTextField grados;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField kilo;
    private javax.swing.JTextField metros;
    private miSwing.miBoton miBoton1;
    private miSwing.miBoton miBoton2;
    private miSwing.miBoton miBoton3;
    private miSwing.miBoton miBoton4;
    private miSwing.miBoton miBoton5;
    private miSwing.miEtiqueta miEtiqueta1;
    private miSwing.miEtiqueta miEtiqueta2;
    private miSwing.miEtiqueta miEtiqueta3;
    private miSwing.miEtiqueta miEtiqueta4;
    private miSwing.miEtiqueta miEtiqueta5;
    private miSwing.miniEnca miniEnca1;
    private javax.swing.JTextField r1;
    private javax.swing.JTextField r2;
    // End of variables declaration//GEN-END:variables
}
