/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GoodMath;

/**
 *
 * @author HP
 */
public class Resistencia extends javax.swing.JFrame {

    
    String Result, Result2, ResulT;
    public Resistencia() {
        super("Resistencias");
        this.setLocation(450, 50);
        initComponents();
        negro1.setVisible(true);
        rojo1.setVisible(false);
        naranja1.setVisible(false);
        amarillo1.setVisible(false);
        verde1.setVisible(false);
        azul1.setVisible(false);
        violeta1.setVisible(false);
        gris1.setVisible(false);
        blanco1.setVisible(false);
        cafe2.setVisible(false);
        rojo2.setVisible(false);
        naranja2.setVisible(false);
        amarillo2.setVisible(false);
        verde2.setVisible(false);
        azul2.setVisible(false);
        violeta2.setVisible(false);
        gris2.setVisible(false);
        blanco2.setVisible(false);
        negro3.setVisible(true);
        cafe3.setVisible(false);
        naranja3.setVisible(false);
        amarillo3.setVisible(false);
        verde3.setVisible(false);
        azul3.setVisible(false);
        violeta3.setVisible(false);
        gris3.setVisible(false);
        blanco3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        blanco1 = new javax.swing.JLabel();
        gris1 = new javax.swing.JLabel();
        violeta1 = new javax.swing.JLabel();
        azul1 = new javax.swing.JLabel();
        verde1 = new javax.swing.JLabel();
        amarillo1 = new javax.swing.JLabel();
        naranja1 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        rojo1 = new javax.swing.JLabel();
        negro1 = new javax.swing.JLabel();
        miniEnca1 = new miSwing.miniEnca();
        r1 = new javax.swing.JComboBox<>();
        botonBack1 = new miSwing.BotonBack();
        blanco2 = new javax.swing.JLabel();
        r2 = new javax.swing.JComboBox<>();
        gris2 = new javax.swing.JLabel();
        violeta2 = new javax.swing.JLabel();
        azul2 = new javax.swing.JLabel();
        verde2 = new javax.swing.JLabel();
        amarillo2 = new javax.swing.JLabel();
        naranja2 = new javax.swing.JLabel();
        rojo2 = new javax.swing.JLabel();
        cafe2 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        blanco3 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        gris3 = new javax.swing.JLabel();
        violeta3 = new javax.swing.JLabel();
        azul3 = new javax.swing.JLabel();
        verde3 = new javax.swing.JLabel();
        amarillo3 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        naranja3 = new javax.swing.JLabel();
        cafe3 = new javax.swing.JLabel();
        negro3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        r3 = new javax.swing.JComboBox<>();
        jSeparator7 = new javax.swing.JSeparator();
        Resultado = new miSwing.miEtiqueta();
        calculadora1 = new miSwing.Calculadora();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        blanco1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/blan.png"))); // NOI18N
        jPanel1.add(blanco1);
        blanco1.setBounds(190, 130, 20, 46);

        gris1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gris.png"))); // NOI18N
        jPanel1.add(gris1);
        gris1.setBounds(190, 130, 20, 46);

        violeta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/vio.png"))); // NOI18N
        jPanel1.add(violeta1);
        violeta1.setBounds(190, 130, 14, 46);

        azul1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/azul.png"))); // NOI18N
        jPanel1.add(azul1);
        azul1.setBounds(190, 130, 14, 46);

        verde1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/verde.png"))); // NOI18N
        jPanel1.add(verde1);
        verde1.setBounds(190, 130, 14, 46);

        amarillo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ama.png"))); // NOI18N
        jPanel1.add(amarillo1);
        amarillo1.setBounds(190, 130, 14, 46);

        naranja1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/naranja.png"))); // NOI18N
        jPanel1.add(naranja1);
        naranja1.setBounds(190, 130, 14, 46);

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator5);
        jSeparator5.setBounds(200, 170, 10, 40);

        rojo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rojo.png"))); // NOI18N
        jPanel1.add(rojo1);
        rojo1.setBounds(190, 130, 14, 46);

        negro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/negro.png"))); // NOI18N
        jPanel1.add(negro1);
        negro1.setBounds(190, 130, 14, 46);
        jPanel1.add(miniEnca1);
        miniEnca1.setBounds(0, 0, 500, 105);

        r1.setFont(new java.awt.Font("Berlin Sans FB", 3, 12)); // NOI18N
        r1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Negro", "Café", "Rojo", "Naranja", "Amarillo", "Verde", "Azul", "Violeta", "Gris", "Blanco" }));
        r1.setToolTipText("Franja 1");
        r1.setBorder(new javax.swing.border.MatteBorder(null));
        r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1ActionPerformed(evt);
            }
        });
        jPanel1.add(r1);
        r1.setBounds(67, 250, 90, 20);

        botonBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBack1ActionPerformed(evt);
            }
        });
        jPanel1.add(botonBack1);
        botonBack1.setBounds(10, 400, 90, 91);

        blanco2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/blan.png"))); // NOI18N
        jPanel1.add(blanco2);
        blanco2.setBounds(220, 126, 14, 50);

        r2.setFont(new java.awt.Font("Berlin Sans FB", 3, 12)); // NOI18N
        r2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Negro", "Café", "Rojo", "Naranja", "Amarillo", "Verde", "Azul", "Violeta", "Gris", "Blanco" }));
        r2.setToolTipText("Franja 1");
        r2.setBorder(new javax.swing.border.MatteBorder(null));
        r2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2ActionPerformed(evt);
            }
        });
        jPanel1.add(r2);
        r2.setBounds(190, 250, 90, 21);

        gris2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gris.png"))); // NOI18N
        jPanel1.add(gris2);
        gris2.setBounds(220, 126, 14, 50);

        violeta2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/vio.png"))); // NOI18N
        jPanel1.add(violeta2);
        violeta2.setBounds(220, 126, 14, 50);

        azul2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/azul.png"))); // NOI18N
        jPanel1.add(azul2);
        azul2.setBounds(220, 126, 14, 50);

        verde2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/verde.png"))); // NOI18N
        jPanel1.add(verde2);
        verde2.setBounds(220, 126, 14, 50);

        amarillo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ama.png"))); // NOI18N
        jPanel1.add(amarillo2);
        amarillo2.setBounds(220, 126, 14, 50);

        naranja2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/naranja.png"))); // NOI18N
        jPanel1.add(naranja2);
        naranja2.setBounds(220, 126, 14, 50);

        rojo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rojo.png"))); // NOI18N
        jPanel1.add(rojo2);
        rojo2.setBounds(220, 126, 14, 50);

        cafe2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cafe.png"))); // NOI18N
        jPanel1.add(cafe2);
        cafe2.setBounds(220, 126, 14, 50);

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator6);
        jSeparator6.setBounds(230, 180, 10, 80);

        blanco3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/blan.png"))); // NOI18N
        jPanel1.add(blanco3);
        blanco3.setBounds(250, 120, 14, 60);
        jPanel1.add(jSeparator8);
        jSeparator8.setBounds(260, 200, 100, 10);

        gris3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gris.png"))); // NOI18N
        jPanel1.add(gris3);
        gris3.setBounds(250, 120, 14, 60);

        violeta3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/vio.png"))); // NOI18N
        jPanel1.add(violeta3);
        violeta3.setBounds(250, 120, 14, 60);

        azul3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/azul.png"))); // NOI18N
        jPanel1.add(azul3);
        azul3.setBounds(250, 120, 14, 60);

        verde3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/verde.png"))); // NOI18N
        jPanel1.add(verde3);
        verde3.setBounds(250, 120, 14, 60);

        amarillo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ama.png"))); // NOI18N
        jPanel1.add(amarillo3);
        amarillo3.setBounds(250, 120, 14, 60);

        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator9);
        jSeparator9.setBounds(260, 170, 10, 30);

        naranja3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/naranja.png"))); // NOI18N
        jPanel1.add(naranja3);
        naranja3.setBounds(250, 120, 14, 60);

        cafe3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cafe.png"))); // NOI18N
        jPanel1.add(cafe3);
        cafe3.setBounds(250, 120, 14, 60);

        negro3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/negro.png"))); // NOI18N
        jPanel1.add(negro3);
        negro3.setBounds(250, 120, 14, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/resistencia.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(110, 100, 280, 120);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(130, 210, 10, 40);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(130, 210, 50, 10);
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(130, 210, 50, 10);
        jPanel1.add(jSeparator4);
        jSeparator4.setBounds(130, 210, 70, 10);

        r3.setFont(new java.awt.Font("Berlin Sans FB", 3, 12)); // NOI18N
        r3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Negro", "Café", "Rojo", "Naranja", "Amarillo", "Verde", "Azul", "Violeta", "Gris", "Blanco" }));
        r3.setToolTipText("Franja 1");
        r3.setBorder(new javax.swing.border.MatteBorder(null));
        r3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3ActionPerformed(evt);
            }
        });
        jPanel1.add(r3);
        r3.setBounds(320, 250, 90, 21);

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator7);
        jSeparator7.setBounds(360, 200, 10, 50);

        Resultado.setText("Valor de Resistencia:");
        jPanel1.add(Resultado);
        Resultado.setBounds(110, 410, 390, 23);

        calculadora1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculadora1ActionPerformed(evt);
            }
        });
        jPanel1.add(calculadora1);
        calculadora1.setBounds(220, 300, 81, 81);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1ActionPerformed
        String op = (String) r1.getSelectedItem();
        if(op.equals("Negro")){
        negro1.setVisible(true);
        rojo1.setVisible(false);
        naranja1.setVisible(false);
        amarillo1.setVisible(false);
        verde1.setVisible(false);
        azul1.setVisible(false);
        violeta1.setVisible(false);
        gris1.setVisible(false);
        blanco1.setVisible(false);
        }
        if(op.equals("Café")){
        negro1.setVisible(false);
        rojo1.setVisible(false);
        naranja1.setVisible(false);
        amarillo1.setVisible(false);
        verde1.setVisible(false);
        azul1.setVisible(false);
        violeta1.setVisible(false);
        gris1.setVisible(false);
        blanco1.setVisible(false);
        }
        if(op.equals("Rojo")){
        rojo1.setVisible(true);
        naranja1.setVisible(false);
        amarillo1.setVisible(false);
        verde1.setVisible(false);
        azul1.setVisible(false);
        violeta1.setVisible(false);
        gris1.setVisible(false);
        blanco1.setVisible(false);
        }
        if(op.equals("Naranja")){
        naranja1.setVisible(true);
        amarillo1.setVisible(false);
        verde1.setVisible(false);
        azul1.setVisible(false);
        violeta1.setVisible(false);
        gris1.setVisible(false);
        blanco1.setVisible(false);
        }
        if(op.equals("Amarillo")){
        amarillo1.setVisible(true);
        verde1.setVisible(false);
        azul1.setVisible(false);
        violeta1.setVisible(false);
        gris1.setVisible(false);
        blanco1.setVisible(false);
        }
        if(op.equals("Verde")){
        verde1.setVisible(true);
        azul1.setVisible(false);
        violeta1.setVisible(false);
        gris1.setVisible(false);
        blanco1.setVisible(false);
        }
        if(op.equals("Azul")){
        azul1.setVisible(true);
        violeta1.setVisible(false);
        gris1.setVisible(false);
        blanco1.setVisible(false);
        }
        if(op.equals("Violeta")){
        violeta1.setVisible(true);
        gris1.setVisible(false);
        blanco1.setVisible(false);
        }
        if(op.equals("Gris")){
        gris1.setVisible(true);
        blanco1.setVisible(false);
        }
        if(op.equals("Blanco")){
            blanco1.setVisible(true);
        }
    }//GEN-LAST:event_r1ActionPerformed

    private void r2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2ActionPerformed
        String op = (String) r2.getSelectedItem();
        if(op.equals("Negro")){
        cafe2.setVisible(false);
        rojo2.setVisible(false);
        naranja2.setVisible(false);
        amarillo2.setVisible(false);
        verde2.setVisible(false);
        azul2.setVisible(false);
        violeta2.setVisible(false);
        gris2.setVisible(false);
        blanco2.setVisible(false);
        }
        if(op.equals("Café")){
        cafe2.setVisible(true);
        rojo2.setVisible(false);
        naranja2.setVisible(false);
        amarillo2.setVisible(false);
        verde2.setVisible(false);
        azul2.setVisible(false);
        violeta2.setVisible(false);
        gris2.setVisible(false);
        blanco2.setVisible(false);
        }
        if(op.equals("Rojo")){
        rojo2.setVisible(true);
        naranja2.setVisible(false);
        amarillo2.setVisible(false);
        verde2.setVisible(false);
        azul2.setVisible(false);
        violeta2.setVisible(false);
        gris2.setVisible(false);
        blanco2.setVisible(false);
        }
        if(op.equals("Naranja")){
        naranja2.setVisible(true);
        amarillo2.setVisible(false);
        verde2.setVisible(false);
        azul2.setVisible(false);
        violeta2.setVisible(false);
        gris2.setVisible(false);
        blanco2.setVisible(false);
        }
        if(op.equals("Amarillo")){
        amarillo2.setVisible(true);
        verde2.setVisible(false);
        azul2.setVisible(false);
        violeta2.setVisible(false);
        gris2.setVisible(false);
        blanco2.setVisible(false);
        }
        if(op.equals("Verde")){
        verde2.setVisible(true);
        azul2.setVisible(false);
        violeta2.setVisible(false);
        gris2.setVisible(false);
        blanco2.setVisible(false);
        }
        if(op.equals("Azul")){
        azul2.setVisible(true);
        violeta2.setVisible(false);
        gris2.setVisible(false);
        blanco2.setVisible(false);
        }
        if(op.equals("Violeta")){
        violeta2.setVisible(true);
        gris2.setVisible(false);
        blanco2.setVisible(false);
        }
        if(op.equals("Gris")){
        gris2.setVisible(true);
        blanco2.setVisible(false);
        }
        if(op.equals("Blanco")){
            blanco2.setVisible(true);
        }
    }//GEN-LAST:event_r2ActionPerformed

    private void r3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3ActionPerformed
        String op = (String) r3.getSelectedItem();
        if(op.equals("Negro")){
        negro3.setVisible(true);
        cafe3.setVisible(false);
        naranja3.setVisible(false);
        amarillo3.setVisible(false);
        verde3.setVisible(false);
        azul3.setVisible(false);
        violeta3.setVisible(false);
        gris3.setVisible(false);
        blanco3.setVisible(false);
        }
        if(op.equals("Café")){
        cafe3.setVisible(true);
        naranja3.setVisible(false);
        amarillo3.setVisible(false);
        verde3.setVisible(false);
        azul3.setVisible(false);
        violeta3.setVisible(false);
        gris3.setVisible(false);
        blanco3.setVisible(false);
        }
        if(op.equals("Rojo")){
        negro3.setVisible(false);
        cafe3.setVisible(false);
        naranja3.setVisible(false);
        amarillo3.setVisible(false);
        verde3.setVisible(false);
        azul3.setVisible(false);
        violeta3.setVisible(false);
        gris3.setVisible(false);
        blanco3.setVisible(false);
        }
        if(op.equals("Naranja")){
        naranja3.setVisible(true);
        amarillo3.setVisible(false);
        verde3.setVisible(false);
        azul3.setVisible(false);
        violeta3.setVisible(false);
        gris3.setVisible(false);
        blanco3.setVisible(false);
        }
        if(op.equals("Amarillo")){
        amarillo3.setVisible(true);
        verde3.setVisible(false);
        azul3.setVisible(false);
        violeta3.setVisible(false);
        gris3.setVisible(false);
        blanco3.setVisible(false);
        }
        if(op.equals("Verde")){
        verde3.setVisible(true);
        azul3.setVisible(false);
        violeta3.setVisible(false);
        gris3.setVisible(false);
        blanco3.setVisible(false);
        }
        if(op.equals("Azul")){
        azul3.setVisible(true);
        violeta3.setVisible(false);
        gris3.setVisible(false);
        blanco3.setVisible(false);
        }
        if(op.equals("Violeta")){
        violeta3.setVisible(true);
        gris3.setVisible(false);
        blanco3.setVisible(false);
        }
        if(op.equals("Gris")){
        gris3.setVisible(true);
        blanco3.setVisible(false);
        }
        if(op.equals("Blanco")){
            blanco3.setVisible(true);
        }
    }//GEN-LAST:event_r3ActionPerformed

    private void botonBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBack1ActionPerformed
        Menu2 menu2 = new Menu2();
        menu2.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonBack1ActionPerformed

    private void calculadora1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculadora1ActionPerformed
        
        String op1 = (String) r1.getSelectedItem();
        if(op1.equals("Negro")){
            Result="";
        }
        if(op1.equals("Café")){
            Result="1";
        }
        if(op1.equals("Rojo")){
            Result="2";
        }
        if(op1.equals("Naranja")){
            Result="3";
        }
        if(op1.equals("Amarillo")){
            Result="4";
        }
        if(op1.equals("Verde")){
            Result="5";
        }
        if(op1.equals("Azul")){
            Result="6";
        }
        if(op1.equals("Violeta")){
            Result="7";
        }
        if(op1.equals("Gris")){
            Result="8";
        }
        if(op1.equals("Blanco")){
            Result="9";
        }
        String op2 = (String) r2.getSelectedItem();
        if(op2.equals("Negro")){
            Result2="";
        }
        if(op2.equals("Café")){
            Result2="1";
        }
        if(op2.equals("Rojo")){
            Result2="2";
        }
        if(op2.equals("Naranja")){
            Result2="3";
        }
        if(op2.equals("Amarillo")){
            Result2="4";
        }
        if(op2.equals("Verde")){
            Result2="5";
        }
        if(op2.equals("Azul")){
            Result2="6";
        }
        if(op2.equals("Violeta")){
            Result2="7";
        }
        if(op2.equals("Gris")){
            Result2="8";
        }
        if(op2.equals("Blanco")){
            Result2="9";
        }
        String op3 = (String) r3.getSelectedItem();
        if(op3.equals("Negro")){
            ResulT=Result+Result2;
        }
        if(op3.equals("Café")){
            ResulT=Result+Result2+"0";
        }
        if(op3.equals("Rojo")){
            ResulT=Result+"."+Result2+"K";
        }
        if(op3.equals("Naranja")){
            ResulT=Result+Result2+"K";
        }
        if(op3.equals("Amarillo")){
            ResulT=Result+Result2+"0K";
        }
        if(op3.equals("Verde")){
            ResulT=Result+"."+Result2+"M";
        }
        if(op3.equals("Azul")){
            ResulT=Result+Result2+"M";
        }
        if(op3.equals("Violeta")){
            ResulT=Result+Result+"0M";
        }
        if(op3.equals("Gris")){
            ResulT=Result+"."+Result2+"G";
        }
        if(op3.equals("Blanco")){
            ResulT=Result+Result2+"G";
        }
        Resultado.setText("Valor de la Resistencia: "+ResulT+" ohms");
    }//GEN-LAST:event_calculadora1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Resistencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private miSwing.miEtiqueta Resultado;
    private javax.swing.JLabel amarillo1;
    private javax.swing.JLabel amarillo2;
    private javax.swing.JLabel amarillo3;
    private javax.swing.JLabel azul1;
    private javax.swing.JLabel azul2;
    private javax.swing.JLabel azul3;
    private javax.swing.JLabel blanco1;
    private javax.swing.JLabel blanco2;
    private javax.swing.JLabel blanco3;
    private miSwing.BotonBack botonBack1;
    private javax.swing.JLabel cafe2;
    private javax.swing.JLabel cafe3;
    private miSwing.Calculadora calculadora1;
    private javax.swing.JLabel gris1;
    private javax.swing.JLabel gris2;
    private javax.swing.JLabel gris3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private miSwing.miniEnca miniEnca1;
    private javax.swing.JLabel naranja1;
    private javax.swing.JLabel naranja2;
    private javax.swing.JLabel naranja3;
    private javax.swing.JLabel negro1;
    private javax.swing.JLabel negro3;
    private javax.swing.JComboBox<String> r1;
    private javax.swing.JComboBox<String> r2;
    private javax.swing.JComboBox<String> r3;
    private javax.swing.JLabel rojo1;
    private javax.swing.JLabel rojo2;
    private javax.swing.JLabel verde1;
    private javax.swing.JLabel verde2;
    private javax.swing.JLabel verde3;
    private javax.swing.JLabel violeta1;
    private javax.swing.JLabel violeta2;
    private javax.swing.JLabel violeta3;
    // End of variables declaration//GEN-END:variables
}
